# Generated by Django 3.0.2 on 2020-01-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200122_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='is_employee',
            new_name='is_usertype',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='is_manager',
        ),
    ]
