# Generated by Django 3.0.2 on 2020-01-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200122_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='is_usertype',
            field=models.CharField(max_length=20),
        ),
    ]
