# Generated by Django 3.0.2 on 2020-01-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200122_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Pdeadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='Pstartdate',
            field=models.DateField(),
        ),
    ]
