# Generated by Django 3.0.2 on 2020-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200122_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Pdeadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='Pstartdate',
            field=models.CharField(max_length=100),
        ),
    ]
