# Generated by Django 3.0.2 on 2020-01-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Tassigneddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='Tdeadline',
            field=models.DateField(),
        ),
    ]
