# Generated by Django 3.0.2 on 2020-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200122_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
