# Generated by Django 3.0.2 on 2020-01-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200124_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='empid',
        ),
        migrations.AlterField(
            model_name='task',
            name='Tassignedto',
            field=models.CharField(max_length=600),
        ),
    ]
