# Generated by Django 3.0.2 on 2020-01-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200124_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='empid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='Tassignedto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userlogin'),
        ),
    ]
