# Generated by Django 3.0.2 on 2020-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200124_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AddField(
            model_name='message',
            name='Mid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_username',
            field=models.CharField(default=2, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(default=2, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=45000),
        ),
    ]
